version: '3'

services:

  postgres:
    container_name: postgres
    image: postgres:13.1
    environment:
      POSTGRES_PASSWORD: "postgres123"
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data: {}
